require 'yaml'
require 'fileutils'
require 'digest/md5'
require 'tmpdir'
require 'pp'

update_steps = [#'nuxeo:download',
                #'nuxeo:prepare',
                'nuxeo:install']

desc "Update Nuxeo installation used by Cloud Foundry"
task :update => update_steps

namespace "nuxeo" do
  desc "Download Nuxeo from nuxeo.com"
  task :download do
    puts "\nStarting Nuxeo download"
    manifest_file = "nuxeo_manifest.yml"
    @manifest = YAML.load_file(manifest_file)
    @download_dest = File.join(Dir.tmpdir, "nuxeo-tomcat-server-#{@manifest['version']}")
    @download_file = @manifest['download_uri'].split("/").last
    puts "\tDownloading Nuxeo v#{@manifest['version']} from '#{@manifest['download_uri']}' to '#{@download_dest}'"
    if File.exists?(@download_dest)
      FileUtils.remove_dir(@download_dest)
    end
    FileUtils.mkdir_p(@download_dest)
    Dir.chdir(@download_dest) do
      system "wget -q -O #{@download_file} #{@manifest['download_uri']}"
      system "wget -q -O #{@download_file}.md5 #{@manifest['md5_uri']}"
      verify_download
    end
    puts "Nuxeo download completed"
  end

  desc "Prepare Nuxeo for CloudFoundry"
  task :prepare => 'nuxeo:download' do
    puts "\nPreparing Nuxeo"
    Dir.chdir(@download_dest) do
      system "unzip -qq #{@download_file}"
      exp_dir = `find . -type d ! -name . | cut -f2 -d\/ | uniq`.split("\n").first
      nuxeo_dir = "nuxeo"
      FileUtils.mv exp_dir, nuxeo_dir
      @targetdir = File.join(@download_dest, nuxeo_dir)
    end
    handle_replace_files
    handle_clear_dirs
    handle_remove_files_and_dirs
    handle_add_jars
    # nuxeo plugins directories does not exists before startup
    FileUtils.mkdir_p(File.join(@targetdir, File.join('nxserver', 'plugins')))
    Dir.chdir(@download_dest) do
      system "zip -q -r nuxeo.zip nuxeo"
    end
    puts "Nuxeo prepare completed"
  end

  desc "Copying Nuxeo into CloudFoundry"
  task :install => 'nuxeo:prepare' do
    puts "\nCopying Nuxeo"
      FileUtils.copy(File.join(@download_dest, "nuxeo.zip"), @manifest['destination'])
    puts "Nuxeo copy completed\n"
  end

  def verify_download
    puts "\tVerifying download"
    digest = Digest::MD5.hexdigest(File.read(@download_file))
    md5sum = IO.readlines("#{@download_file}.md5")[0].split[0]
    raise "MD5Sum verification check failed" unless digest == md5sum
  end

  def handle_replace_files
    @manifest['replace_files'].each do |file|
      target_file = File.join(@targetdir, file)
      source_file = File.join("resources", file)
      puts "\tReplacing '#{target_file}' with '#{source_file}'"
      FileUtils.remove(target_file)
      FileUtils.copy(source_file, target_file)
    end
  end

  def handle_clear_dirs
    @manifest['clear_dirs'].each do |file|
      target_file = File.join(@targetdir, file)
      puts "\tClearing '#{target_file}'"
      Dir.chdir target_file do
        FileUtils.rm_r Dir.glob('*')
      end
    end
  end

  def handle_remove_files_and_dirs
    @manifest['remove_files'].each do |file|
      target_file = File.join(@targetdir, file)
      puts "\tRemoving '#{target_file}'"
      FileUtils.rm_r target_file
    end
  end

  def handle_add_jars
    @manifest['add_jars'].each do |file|
      target_file = File.join(@targetdir, file)
      source_file = File.join("resources", file)
      puts "\tCopying jar '#{source_file}' to '#{target_file}"
      FileUtils.copy(source_file, target_file)
    end
  end

end
